### ISSUE TITLE
It will appear a new icon on Gnome dock if I have pin it on the Gnome dock.

### ISSUE THREAD

**Issue by laichiaheng** [abba23/spotify-adblock-linux#1]
There are 2 icons if I have pin it on Gnome dock.

**Comment by abba23** [comment]
I'm not sure what you mean exactly. If you're talking about the AUR package, then there are supposed to be two desktop entries. The original one that comes with the Spotify package and a new modified one that preloads the adblocking library file.

**Comment by laichiaheng** [comment]
Yes, I put the preloading one on the dock, but it will open another icon on dock.
![2019-04-26 21-42-43 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/56811867-4a129800-686c-11e9-990e-05940c10b666.png)

**Comment by abba23** [comment]
I don't know why that happens, but it looks like that's a problem with Gnome, which I can't really do anything about anyway.

**Comment by laichiaheng** [comment]
@abba23 The temporary solution is to replace the spotify desktop icon by spotify (adblock)
