### ISSUE TITLE
[1]    13256 segmentation fault (core dumped)

### ISSUE THREAD

**Issue by the-lotuseater** [abba23/spotify-adblock-linux#10]
System- Manjaro Illyria KDE / Kernel 4.19-66
Reproduce bug- $LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify

Can I add set LD_PRELOAD variable in my .zshrc and take care of this?

**Comment by the-lotuseater** [comment]
Tried adding to my zshrc file but no luck. Still seeing adds.

**Comment by abba23** [comment]
I can't reproduce that error. When does it happen exactly? On launch or later on? Does Spotify start at all? Is there any other output before the error?

**Comment by the-lotuseater** [comment]
Spotify works, but I see this message -
Gtk-Message: Failed to load module "canberra-gtk-module"
[0823/162619.975547:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

After a couple hours I get this message-
 2019/08/20 17:58:55:6288] ERR: getaddrinfo failed: -2

**Comment by abba23** [comment]
Those error messages can be safely ignored then.
