### ISSUE TITLE
Can't upload playlist image

### ISSUE THREAD

**Issue by mariansam** [abba23/spotify-adblock-linux#100]
### Steps to reproduce
1. create a playlist
2. click on it's thumbnail picture to change playlist details
3. click on the thumbnail picture to upload a new one
4. select a valid JPEG file
5. click Save

### Actual result
The error message *Failed to save playlist changes. Please try again.* pops up.

### Expected result
The image gets uploaded.

### Reason
As the output says:
```console
[-] getaddrinfo:                image-upload4.spotify.com
```
These image upload domains should be white-listed, but aren't.

**Comment by abba23** [comment]
Thanks for the report! It should be fixed now. (82c0bf470d71ca2533cbc0f79d50ae0f8f8bf90c)

**Comment by mariansam** [comment]
Big thanks. Works. Closing.
