### ISSUE TITLE
[Request] Discord Support server for Spotify adblocks.

### ISSUE THREAD

**Issue by rednek46** [abba23/spotify-adblock-linux#101]
Hello, 
I'm a maintainer at [BlockTheSpot Windows](https://github.com/mrpond/BlockTheSpot).  We recently started a discord support server for Spotify adblocks. Would you like to add this repo on the support as well @abba23 ?

**Comment by abba23** [comment]
Sure, I don't use Discord myself, but you're free to povide support for this project if you like.

**Comment by rednek46** [comment]
nice. I will add an invite widget to the readme.

**Comment by abba23** [comment]
I'm sorry, but I think there has been a misunderstanding. As I said, you're of course free to help people on your Discord server out if they encounter a problem with this project. I don't want to actively refer people to or endorse support on a platform and by people I don't know, though.

**Comment by rednek46** [comment]
ok. thanks
