### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by thenoobtester** [abba23/spotify-adblock-linux#104]
Hi,

I tried to compile but don''t get anything. When I run make it just outputs this:

`gcc -Wall -I. -shared -fPIC -o spotify-adblock.so  -ldl spotify-adblock.c whitelist.h blacklist.h`

but it doesn't generate the .so file. I tried removing the dot after -I. but then I get :

_In file included from spotify-adblock.c:9:0:
include/capi/cef_urlrequest_capi.h:43:10: fatal error: include/capi/cef_auth_callback_capi.h: No such file or directory
 #include "include/capi/cef_auth_callback_capi.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated._

I tried compiling because after downling the released .so I get this error (notice I use an appimaged Spotify):

_dlsym (curl_easy_setopt): /usr/local/lib/spotify-adblock.so: undefined symbol: curl_easy_setopt
dlsym (cef_urlrequest_create): /usr/local/lib/spotify-adblock.so: undefined symbol: cef_urlrequest_create
./Spotify-x86_64.AppImage: symbol lookup error: /usr/local/lib/spotify-adblock.so: undefined symbol: dlsym_

Debian 9 stretch/Ubuntu 18.04.5 LTS (Bionic Beaver)

Kindest regards,
Thank you

PS: I just found out the -I flag meant include directory, so the . meant current directory.

**Comment by thenoobtester** [comment]
My mistake, I was compiling on a remote server and for whatever reason the file explorer was hiding the .so files. :)

**Comment by abba23** [comment]
Looks like the main problem has already solved itself. As for the second one:

>notice I use an appimaged Spotify

I've never tested this with an AppImage, but I imagine that it wouldn't work for similar reasons that it doesn't work with snap or Flatpak packages. Try using Spotify's Debian package instead. You can find the installation instructions at the bottom of [this page](https://www.spotify.com/us/download/linux).
