### ISSUE TITLE
The requested URL returned error: 404 - Installing package from AUR

### ISSUE THREAD

**Issue by dakata1337** [abba23/spotify-adblock-linux#106]
Hello everyone!
When I try to install spotify-adblock-linux from AUR i get this error:
```
==> ERROR: Failure while downloading http://opensource.spotify.com/cefbuilds/cef_binary_80.0.8%2Bgf96cd1d%2Bchromium-80.0.3987.132_linux64_minimal.tar.bz2
```

I installed the package manually but it still tries to install it from the URI above.

**Comment by abba23** [comment]
Should be fixed now. In the future, if you have a problem with an AUR package, please just leave a comment on the corresponding AUR page to alert its maintainers.

**Comment by dakata1337** [comment]
> Should be fixed now. In the future, if you have a problem with an AUR package, please just leave a comment on the corresponding AUR page to alert its maintainers.

Ok, thanks.
