### ISSUE TITLE
Ted Talks podcasts

### ISSUE THREAD

**Issue by Puncia** [abba23/spotify-adblock-linux#109]
After some trial and error I think these URLs need to be added to `whitelist.h` in order to listen to Ted Talks (https://open.spotify.com/show/1VXcH8QHkjRcTCEd88U3ti?si=4dmQUk8MQ7u2oEfzwVfKHA)
```
"dts.podtrac.com",
"download.ted.com",
"dovetail.prxu.org",
"dovetail-cdn.prxu.org"
```

**Comment by abba23** [comment]
Thanks for the report! I've just added those domains to the whitelist.

**Comment by Syzygianinfern0** [comment]
@Puncia Is it [this](https://open.spotify.com/show/1VXcH8QHkjRcTCEd88U3ti?si=yg2IVsggTt6NNp4wqlyc-w) one?
