### ISSUE TITLE
Some tracks are getting blocked 

### ISSUE THREAD

**Issue by nokatt** [abba23/spotify-adblock-linux#11]
For instance [this track](https://open.spotify.com/album/59ehepoM66cQr056fxJsNW) can't be played with the client but will get played in browser with Ublock or in the modified Android app. I noticed this problem with a few other tracks but I forgot to open an issue back then. 

<sup>Don't judge my music taste I'm just searching for some new phonk 😳</sup>

**Comment by abba23** [comment]
All the tracks from that album play fine for me in the desktop client. Sometimes it takes a few seconds longer to load a page when it's trying to make some ad-related requests first, but I haven't come across anything yet that wouldn't load at all.

Can you try running it from a terminal and check the output for any blocked requests (indicated by the line beginning with a `[-]`) when you try to play those tracks?

**Comment by nokatt** [comment]
That's weird now it's also running for me. Yesterday the track wouldn't start at all and I'm sure I kept it on play while I checked it on my browser. I also played other tracks and tried to play it again with no success.

If I stumble across this issue in the future I'm going to use the terminal. Thank you for your help.
