### ISSUE TITLE
Your version is now old please update it.. Spotify version 1.1.55.498.gf9a83c60 is the new version..

### ISSUE THREAD

**Issue by ghostinlinux** [abba23/spotify-adblock-linux#110]

**Comment by abba23** [comment]
Please provide a bit more context. Assuming this is an error message, where are you seeing it and why do you think it's related to this adblocker?

**Comment by ghostinlinux** [comment]
> Please provide a bit more context. Assuming this is an error message, where are you seeing it and why do you think it's related to this adblocker?

When i upgraded my packages spotify is also upgraded to its newer version then i open spotify ad blocker then a white screen appears... and it is not working...

**Comment by abba23** [comment]
Did you also update the adblocker? It should be working with the latest commit. If that's what you're using already, then I'll need the terminal output to debug.
