### ISSUE TITLE
New spotify's daily mixes images and podcast whitelist

### ISSUE THREAD

**Issue by TheLich132** [abba23/spotify-adblock-linux#113]
Spotify recently has added new mixes and they art images of these playlists weren't loading. Also ["Dwóch Typów Podcast"](https://open.spotify.com/show/1BXx0x8FKNN1R6qxuC3aqv) podcasts weren't loading at all. I've tried running spotify with adblock through terminal and after whitelisting this addresses these two things has started working properly.

```
"seed-mix-image.spotifycdn.com",
"*.podbean.com"
```

**Comment by abba23** [comment]
Thanks for the report! I've added both to the whitelist.
