### ISSUE TITLE
Scalling issues on Hi-DPI

### ISSUE THREAD

**Issue by pranavkarande** [abba23/spotify-adblock-linux#117]
Is there as way to set a scale factor for eg. 1.25x for hi-dpi displays where icons and fonts are too small.

**Comment by abba23** [comment]
How is that related to adblocking?

**Comment by realnc** [comment]
> Is there as way to set a scale factor for eg. 1.25x for hi-dpi displays where icons and fonts are too small.

This is off-topic here of course, but here's how you do it. Launch spotify with the `--force-device-scale-factor=1.25` command line option.
