### ISSUE TITLE
feature: add whitelist / blacklist entries via environment variables

### ISSUE THREAD

**Issue by milahu** [abba23/spotify-adblock-linux#119]
title says all : )

for testing/prototyping it would be useful to add entries to whitelist or blacklist, without having to recompile `spotify-adblock.so`

**Comment by AvinashReddy3108** [comment]
> title says all : )
> 
> for testing/prototyping it would be useful to add entries to whitelist or blacklist, without having to recompile `spotify-adblock.so`

For testing/prototyping, I suggest the `.txt` file approach.
Just add your stuff into the appropriate `blacklist.txt` or `whitelist.txt` and done.

**Comment by abba23** [comment]
I don't really see the benefit of such a feature. The only difference would be that you don't have to run `make` before testing, which should take less than a second anyway.

**Comment by milahu** [comment]
> Just add your stuff into the appropriate `blacklist.txt` or `whitelist.txt` and done.

you mean `blacklist.h` and `whitelist.h`?

> I don't really see the benefit

im [packaging](https://github.com/milahu/nur-packages/tree/master/pkgs/spotify-adblock-linux) this for nixos
and with this feature, we could avoid to rebuild the whole package
in nixos, i could split the package into smaller modules, so the rebuild is faster,
but this would also help with other binary releases (docker, snap, flatpak, appimage ...)
where a rebuild may be not-so-easy

would you accept a PR?

**Comment by abba23** [comment]
If we were to do this, I think the way to go would be to have an actual config file. I.e. something like `/etc/spotify-adblock.yaml`, which can be overridden in `~/.config/spotify-adblock.yaml` and contains:

```yaml
debug: true
whitelist:
  - example.org
  - spotify.com
blacklist:
  - https://example.org/ads/*
  - https://spotify.com/tracking
```

That said, I don't see how it would benefit packaging either. As I said before, a normal build should take less than a second. Packaging a single shared object using Docker, Snap etc. seems like a rather theoretical use case and I'm not even certain that it would actually take much longer.

I do agree that using header files for this is a bit of a hack and having a config file would be much more elegant. File handling, parsing and error handling on the other hand would add a large amount of code and maybe new dependencies to the project, which I'm not sure can be justified like this.

**Comment by milahu** [comment]
zero cost solution: use the same config-parser as spotify

see `~/.config/spotify/prefs` - this looks like a [glib key-val file](https://stackoverflow.com/a/2252706/10440128)

```
ldd spotify | grep glib
libglib-2.0.so.0
```

<details>
<summary>re: Packaging a single shared object</summary>

> Packaging a single shared object using Docker, Snap etc. seems like a rather theoretical use case

im packaging spotify + spotify-adblock.so into a single package, wrapped in /bin/spotify-adblock-linux

the most build time is spent on extracting the 300 MB cef_build.tar.bz2
only cos i did not yet factor-out the cef_build/include directory into a separate package ...

> [...] would add a large amount of code and maybe new dependencies to the project, which I'm not sure can be justified like this.

</details>

**Comment by milahu** [comment]
> zero cost solution: use the same config-parser as spotify

downside: that config format only allows key-value pairs
but for whitelist and blacklist we need arrays of strings
-> now using [yaml](https://github.com/yaml/libyaml)

**Comment by abba23** [comment]
I've recently been playing around with Rust a bit and tried reimplementing this project today (see https://github.com/abba23/spotify-adblock). The result supports configuration via a `config.toml` file.
