### ISSUE TITLE
Question: can Spotify somehow find out I'm using this app?

### ISSUE THREAD

**Issue by pervoj** [abba23/spotify-adblock-linux#122]
I tried this app, and it's amazing, but in Spotify's terms of use they prohibit ad blocking. So, my question is, can Spotify somehow find out I'm using this app?

**Comment by abba23** [comment]
Yes, it would certainly be possible for Spotify to e.g. check for accounts that are active, but never query any of their ad-related APIs. That said, I've been blocking ads in Spotify for years and nothing has ever happened. I'll close this, since it's not actually an issue.

**Comment by pervoj** [comment]
Thanks
