### ISSUE TITLE
nothing to be done for 'all'

### ISSUE THREAD

**Issue by nonvieri** [abba23/spotify-adblock-linux#124]
i get this 
![Screenshot from 2021-04-27 03-51-55 (copy)](https://user-images.githubusercontent.com/46636729/116198458-57d5af00-a70c-11eb-897a-ba8d98893647.png)

**Comment by abba23** [comment]
That just means there haven't been any changes since you last ran `make`, so nothing has to be rebuilt. Is anything not working?

**Comment by nonvieri** [comment]
yes
![Screenshot from 2021-04-27 04-27-00](https://user-images.githubusercontent.com/46636729/116202385-e3e9d580-a710-11eb-86b1-ae565db077db.png)

**Comment by abba23** [comment]
See #78. As mentioned in the readme, this doesn't work with the snap version of Spotify. The Ubuntu store installs the snap package by default for some applications. You can install the Debian package by following the instructions at the bottom of [this page](https://www.spotify.com/us/download/linux/). Don't forget to uninstall the snap version first.

**Comment by nonvieri** [comment]
![Screenshot from 2021-04-27 04-43-24](https://user-images.githubusercontent.com/46636729/116204401-1e547200-a713-11eb-9470-184b46bd2eeb.png)

**Comment by abba23** [comment]
There's no error. Just do what it says in the instructions.

**Comment by nonvieri** [comment]
I just did, it says unable to fetch some archived, and even updating it doesn't install
