### ISSUE TITLE
(UNIX) Mac Support

### ISSUE THREAD

**Issue by Shabinder** [abba23/spotify-adblock-linux#126]
Hey as Linux and Mac are both UNIX-based, is there any possibility that you will consider adding support for MacOS too?

**Comment by abba23** [comment]
I don't use macOS, so that's not really something I'd be able to maintain. There is however [a fork of this project targeted at macOS](https://github.com/Dark-Matter7232/spotify-adblock-mac). It might be a bit out of date though.

**Comment by Shabinder** [comment]
Ohh I see
