### ISSUE TITLE
use launcher as default spotify

### ISSUE THREAD

**Issue by nonvieri** [abba23/spotify-adblock-linux#128]
is there some way to make ubuntu recognise the launcher as default spotify app?

i.e. when i click on links that lead to open spotify application, it opens the non-adblocked version

**Comment by abba23** [comment]
Which application handles Spotify links should be configurable in your browser settings.

Alternatively, you could override the original Spotify launcher by renaming the one you created in `~/.local/share/applications` to have the same name as the original one in `/usr/share/applications` (probably `spotify.desktop`).

**Comment by nonvieri** [comment]
thank you so much. by the way, the adblock works fine for 'alpha' client version, it just has this blank ad space below

![Screenshot from 2021-05-04 11-39-24](https://user-images.githubusercontent.com/46636729/117021255-913e8980-accd-11eb-8565-f9e387ae8519.png)
