### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by victorawogbemi** [abba23/spotify-adblock-linux#13]
when I use make i got this error 

gcc -Wall -shared -fPIC -o spotify-adblock.so -ldl spotify-adblock.c whitelist.h blacklist.h
spotify-adblock.c:3:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:11: recipe for target 'spotify-adblock.so' failed
make: *** [spotify-adblock.so] Error 1

**Comment by abba23** [comment]
Looks like you're missing the *libcurl* headers. The package's name differs depending on your Linux distribution. On Ubuntu and related distributions, you should be able to install it using `sudo apt install libcurl4-gnutls-dev`.

I should probably

**Comment by victorawogbemi** [comment]
Thank you, it worked!
