### ISSUE TITLE
spotify-adblock-linux Automated

### ISSUE THREAD

**Issue by Ramzh** [abba23/spotify-adblock-linux#17]
Would be great if it's possible to add in the readme:

If you want it to work automatically, it's easy. First you open the .desktop file

`sudo nano /usr/share/applications/spotify.desktop`

You can replace nano for any editor you want.

Then you change the line

`Exec=spotify %U`

to

`Exec=env LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify %U`

Then it should work automatically when you open it from your desktop environment.

**Comment by polyzen** [comment]
Files in such locations are not meant to be edited manually. Install a supplementary desktop file, like https://aur.archlinux.org/cgit/aur.git/tree/spotify-adblock.desktop?h=spotify-adblock-git

**Comment by Ramzh** [comment]
Ah did not know, add a supplementary file as mentioned and it's working! Thank you good sir! Still worth mentioning in the readme I believe
