### ISSUE TITLE
Spotify deleting my account

### ISSUE THREAD

**Issue by 987454611235** [abba23/spotify-adblock-linux#18]
Seems to be working, as I get no ads. But Spotify doesn't like those who won't give them personal data.

Took around 24 hours before they took it down. 
"Your session has been terminated. (Error code: 127)"

env LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
/usr/lib64/spotify-client/spotify: /usr/lib64/spotify-client/libcurl-gnutls.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
Gtk-Message: 21:24:57.313: Failed to load module "canberra-gtk-module"
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
/usr/share/spotify-client/spotify: /usr/lib64/spotify-client/libcurl-gnutls.so.4: no version information available (required by /usr/share/spotify-client/spotify)
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
/proc/self/exe: /usr/lib64/spotify-client/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[2019/09/20 00:02:23:7106] ERR: getaddrinfo failed
[2019/09/20 00:02:57:1585] ERR: getaddrinfo failed

Fedora 30
Verified Protonmail e-mail
Connection over Tor
Spotify version 1.1.5.153.gf614956d

**Comment by abba23** [comment]
Are you absolutely sure your account has been deleted? Are you unable to login through their website too? I've been using this for months and never had any problem like that.

That log looks more like the shared library file hasn't been compiled correctly. Can you try building it again and check if there are any errors during compilation? You could also try deleting Spotify's cache (`~/.cache/spotify` I believe).

**Comment by 987454611235** [comment]
[+] spclient.wg.spotify.com
[+] apresolve.spotify.com
[-] open.spotify.com
[-] open.spotify.com
[-] open.spotify.com
[-] open.spotify.com
[-] open.spotify.com
[-] sentry.io


I get normal logs now, but another account got deleted. And that last line, "sentry.io" is just sending the error code to them? "Your session has been terminated". 

Will try again with another connection, not over Tor.

**Comment by LinArcX** [comment]
Yeah, tor will delete your account. Don't use spotify with it.

**Comment by abba23** [comment]
I'll close this then. Please create another issue if you have the same problem without Tor.
