### ISSUE TITLE
Provide a release version

### ISSUE THREAD

**Issue by LinArcX** [abba23/spotify-adblock-linux#19]
Hi. and thank you for this great effort. i'm using void-linux and want to package `spotify-adblock-linux` for it. But they only accept released version of package:
https://github.com/void-linux/void-packages/issues/14683
So please provide it.
Thank you so much.

**Comment by abba23** [comment]
Hey, thanks for your interest in packaging this project. I just created a first release from the current master branch state. Have fun!

**Comment by LinArcX** [comment]
Wow! thank you so much.
