### ISSUE TITLE
spotify-adblock.c:3:10: fatal error: curl/curl.h: No such file or directory

### ISSUE THREAD

**Issue by LinkPhoenix** [abba23/spotify-adblock-linux#26]
If you have this issue

launch

sudo apt-get install libcurl4-openssl-dev

**Comment by abba23** [comment]
Thanks for the reminder. This has been reported before, but I hadn't made note of it in the readme. I've now added a list of build prerequisites.

**Comment by LinkPhoenix** [comment]
Suoper thank you and great job

**Comment by StellarisStudio** [comment]
If you use Opensuse it's libcurl-devel

sudo zypper in libcurl-devel
