### ISSUE TITLE
when building, I get error 127

### ISSUE THREAD

**Issue by athaun** [abba23/spotify-adblock-linux#3]
after following the steps in the readme, I got this error when I ran `make`
`gcc -Wall -shared -fPIC -o spotify-adblock.so -ldl spotify-adblock.c whitelist.h
make: gcc: Command not found
Makefile:9: recipe for target 'spotify-adblock.so' failed
make: *** [spotify-adblock.so] Error 127
`

**Comment by abba23** [comment]
>`gcc: Command not found`

You're missing GCC. Install GCC.

**Comment by athaun** [comment]
Thanks!
