### ISSUE TITLE
ads not stopped totally just became more less frequent

### ISSUE THREAD

**Issue by benciboy** [abba23/spotify-adblock-linux#30]
Hi, 

after building and running your code, the number of ads has been decreased significantly but sometimes get them.
My question how can monitor which domain are used for ads to blacklist them?
Im using spotify latest snap version on ubunutu 16.04:
spotify            1.1.10.546.ge08ef575-19     36     stable    spotify✓ 
mostly in Hungary.

I've been trying wireshark, tcpdump to monitor connections, but here are to many of them without name resolution, so can't debug in this way.

Br 
B.

**Comment by abba23** [comment]
This adblocker does not work with the snap Spotify package. I've now added a note about that to the readme.

**Comment by benciboy** [comment]
it' s looks like is solved with non snap client.
Thanks.

**Comment by kerbless** [comment]
spotify-client (1:1.1.10.546.ge08ef575-19) Non snap client, same issue.

**Comment by abba23** [comment]
If you're not using the snap client, then your problem appears to be different to the one that was solved in this issue. Please open a separate issue and make sure to include the terminal output from compilation and the Spotify client.
