### ISSUE TITLE
Ads still playing, just less frequent (banner ads are not displayed)

### ISSUE THREAD

**Issue by kerbless** [abba23/spotify-adblock-linux#31]
spotify-client (1:1.1.10.546.ge08ef575-19)

Installed via the official repository.
Running on Debian 10 with Gnome.
One ad provider: https://ad.doubleclick.net/

output of "sudo make --debug install":
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating makefiles....
Updating goal targets....
 File 'install' does not exist.
Must remake target 'install'.
install -Dm644 -t /usr/local/lib spotify-adblock.so
Successfully remade target file 'install'.

output of "LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify": [1125/172058.267787:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

**Comment by abba23** [comment]
>output of "D_PRELOAD=/usr/local/lib/spotify-adblock.so spotify"

The environment variable is called `LD_PRELOAD`.

**Comment by kerbless** [comment]
> > output of "D_PRELOAD=/usr/local/lib/spotify-adblock.so spotify"
> 
> The environment variable is called `LD_PRELOAD`.

Just a typing error sorry. Spotify runs as expected, the output is the same.

**Comment by abba23** [comment]
Then please try removing the `spotify-adblock.so` file from the build directory and run `sudo make install` again. As long as the file still exists, `make` won't try to rebuild it, which seems to have happened when you just ran it.

I'm not sure why banner ads aren't appearing for you though. If anything had been blocked there should have been some corresponding terminal output.

**Comment by kerbless** [comment]
unistalled and reinstalled, now when I run "LD_PRELOAD..." I get this:
`ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
[1126/133634.614051:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
`

**Comment by abba23** [comment]
Were there any errors during compilation?

**Comment by kerbless** [comment]
No

**Comment by abba23** [comment]
>unistalled and reinstalled

Just to make sure, you did actually remove the `spotify-adblock.so` file from the build directory and didn't just run `sudo make uninstall` and `sudo make install`, right?

If that's the case and there were no errors at all, then I have no idea what the problem could be. Maybe try cloning the repo again to a different folder and building from there. If that doesn't work, I can't really help you any further.

**Comment by kerbless** [comment]
Tried both ways. No compilation errors, but I get that messages when I run
the DL command

**Comment by kerbless** [comment]
Fixed:
I removed and resinstalled `libcurl4-openssl-dev`.
I ran `sudo make uninstall` and then `make clean`.
Then I reinstalled with `sudo make install` and started working.
