### ISSUE TITLE
Still getting ads

### ISSUE THREAD

**Issue by carlos12silva94** [abba23/spotify-adblock-linux#34]
Running this:
LD_PRELOAD=/usr/local/lib/spotify-adblock.so snap run spotify &

i see this errors:
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
[1210/144406.180554:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

Spotify works, however i still see ads and listen to them

**Comment by abba23** [comment]
As noted in the readme, this does not work with the snap Spotify package.

**Comment by carlos12silva94** [comment]
OK. didnt saw that
