### ISSUE TITLE
Still seeing ads

### ISSUE THREAD

**Issue by carlos12silva94** [abba23/spotify-adblock-linux#35]
Now im using the store version, but i still have 100% of ads

**Comment by abba23** [comment]
Please provide a bit more information. What commands did you run exactly? What was their output? By 'store', do you mean the Ubuntu Software Center?

**Comment by carlos12silva94** [comment]
Yeah i mean software center.
just running this:
LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify &

is there any way to see more logs?

**Comment by abba23** [comment]
>just running this:
LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify &

What was its output? Which commands did you run to compile and install it and what was their output?

**Comment by carlos12silva94** [comment]
$ LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify &
[1] 30643
$ Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
[1210/164908.781148:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

The install process went well, i just run the commands you have on the read me

**Comment by carlos12silva94** [comment]
spotify-adblock-linux$ make
make: Nothing to be done for 'all'.

**Comment by abba23** [comment]
Please run `make clean` before running `make` again. Otherwise it won't be built again and you won't see any errors.

Did you install `libcurl4-gnutls-dev` as instructed?

**Comment by carlos12silva94** [comment]
yeah, i've installed that.
after a clean:
```
$make
gcc -Wall -shared -fPIC -o spotify-adblock.so  -ldl spotify-adblock.c whitelist.h blacklist.h

```

**Comment by abba23** [comment]
That seems to be fine then. Are you sure that the Ubuntu Software Center didn't just install the snap package again? Can you try installing Spotify using the instructions at the bottom of [this page](https://www.spotify.com/us/download/linux)?

**Comment by carlos12silva94** [comment]
I did that. but now, i cant see ads, neither album images, neither friends radar. Also cant play any song:

`[+] apresolve.spotify.com
[+] gew1-accesspoint-a-2dwr.ap.spotify.com
[+] dealer.spotify.com
[+] dealer.spotify.com
[-] https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXRcLzUzNi41IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC8xOS4wLjEwODQuOSBTYWZhcmlcLzUzNi41IFNwb3RpZnlcLzExMTAwMDU0NiAoODsgMDsgNSkiLCJzZXNzaW9uX2lkIjoiNmM1YzBjZDgtMjk4OS00OWIzLTkzMGEtNmE2NDYxZDNlMjRmIn0=
[+] dealer.spotify.com
[+] dealer.spotify.com
[-] https://spclient.wg.spotify.com/ad-logic/v1/config
[+] https://spclient.wg.spotify.com/reaccept-my-legal/v1/reacceptance-metadata?language=en
[+] spclient.wg.spotify.com
[-] https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXRcLzUzNi41IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC8xOS4wLjEwODQuOSBTYWZhcmlcLzUzNi41IFNwb3RpZnlcLzExMTAwMDU0NiAoODsgMDsgNSkiLCJzZXNzaW9uX2lkIjoiNmM1YzBjZDgtMjk4OS00OWIzLTkzMGEtNmE2NDYxZDNlMjRmIn0=
[-] https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXRcLzUzNi41IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC8xOS4wLjEwODQuOSBTYWZhcmlcLzUzNi41IFNwb3RpZnlcLzExMTAwMDU0NiAoODsgMDsgNSkiLCJzZXNzaW9uX2lkIjoiNmM1YzBjZDgtMjk4OS00OWIzLTkzMGEtNmE2NDYxZDNlMjRmIn0=
[-] https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXRcLzUzNi41IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC8xOS4wLjEwODQuOSBTYWZhcmlcLzUzNi41IFNwb3RpZnlcLzExMTAwMDU0NiAoODsgMDsgNSkiLCJzZXNzaW9uX2lkIjoiNmM1YzBjZDgtMjk4OS00OWIzLTkzMGEtNmE2NDYxZDNlMjRmIn0=
[-] https://spclient.wg.spotify.com/ad-logic/v1/config
[-] https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXRcLzUzNi41IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC8xOS4wLjEwODQuOSBTYWZhcmlcLzUzNi41IFNwb3RpZnlcLzExMTAwMDU0NiAoODsgMDsgNSkiLCJzZXNzaW9uX2lkIjoiNmM1YzBjZDgtMjk4OS00OWIzLTkzMGEtNmE2NDYxZDNlMjRmIn0=
[-] https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXRcLzUzNi41IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC8xOS4wLjEwODQuOSBTYWZhcmlcLzUzNi41IFNwb3RpZnlcLzExMTAwMDU0NiAoODsgMDsgNSkiLCJzZXNzaW9uX2lkIjoiNmM1YzBjZDgtMjk4OS00OWIzLTkzMGEtNmE2NDYxZDNlMjRmIn0=
[-] https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXRcLzUzNi41IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC8xOS4wLjEwODQuOSBTYWZhcmlcLzUzNi41IFNwb3RpZnlcLzExMTAwMDU0NiAoODsgMDsgNSkiLCJzZXNzaW9uX2lkIjoiNmM1YzBjZDgtMjk4OS00OWIzLTkzMGEtNmE2NDYxZDNlMjRmIn0=
[-] https://spclient.wg.spotify.com/ad-logic/v1/config
[-] https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXRcLzUzNi41IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC8xOS4wLjEwODQuOSBTYWZhcmlcLzUzNi41IFNwb3RpZnlcLzExMTAwMDU0NiAoODsgMDsgNSkiLCJzZXNzaW9uX2lkIjoiNmM1YzBjZDgtMjk4OS00OWIzLTkzMGEtNmE2NDYxZDNlMjRmIn0=
[-] https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXRcLzUzNi41IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC8xOS4wLjEwODQuOSBTYWZhcmlcLzUzNi41IFNwb3RpZnlcLzExMTAwMDU0NiAoODsgMDsgNSkiLCJzZXNzaW9uX2lkIjoiNmM1YzBjZDgtMjk4OS00OWIzLTkzMGEtNmE2NDYxZDNlMjRmIn0=
[-] https://spclient.wg.spotify.com/ad-logic/v1/config
[-] https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXRcLzUzNi41IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC8xOS4wLjEwODQuOSBTYWZhcmlcLzUzNi41IFNwb3RpZnlcLzExMTAwMDU0NiAoODsgMDsgNSkiLCJzZXNzaW9uX2lkIjoiNmM1YzBjZDgtMjk4OS00OWIzLTkzMGEtNmE2NDYxZDNlMjRmIn0=
[+] https://spclient.wg.spotify.com/playlist-publish/v1/subscription/playlist/37i9dQZF1DX0rV7skaITBo
[+] https://spclient.wg.spotify.com/playlist-publish/v1/subscription/playlist/37i9dQZF1DWVovHcLREwOK
[+] https://spclient.wg.spotify.com/playlist-publish/v1/subscription/playlist/37i9dQZF1DX6ViL9RcFABv
[+] https://spclient.wg.spotify.com/playlist-publish/v1/subscription/playlist/37i9dQZF1DX4WYpdgoIcn6
[+] https://spclient.wg.spotify.com/playlist-publish/v1/subscription/playlist/37i9dQZF1DWUPwR1fjNPQr
[+] https://spclient.wg.spotify.com/playlist-publish/v1/subscription/playlist/37i9dQZF1DXcBWIGoYBM5M
[+] https://spclient.wg.spotify.com/playlist-publish/v1/subscription/playlist/37i9dQZF1DWSoyxGghlqv5
[+] https://spclient.wg.spotify.com/playlist-publish/v1/subscription/playlist/37i9dQZF1DX56qfiUZBncF
[+] https://spclient.wg.spotify.com/playlist-publish/v1/subscription/playlist/37i9dQZF1DX2TRYkJECvfC
[+] https://spclient.wg.spotify.com/playlist-publish/v1/subscription/playlist/37i9dQZF1DX0XUsuxWHRQd
[+] https://spclient.wg.spotify.com/playlist-publish/v1/subscription/playlist/37i9dQZF1DXcF6B6QPhFDv
[-] https://spclient.wg.spotify.com/ad-logic/v1/config
[-] https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXRcLzUzNi41IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC8xOS4wLjEwODQuOSBTYWZhcmlcLzUzNi41IFNwb3RpZnlcLzExMTAwMDU0NiAoODsgMDsgNSkiLCJzZXNzaW9uX2lkIjoiNmM1YzBjZDgtMjk4OS00OWIzLTkzMGEtNmE2NDYxZDNlMjRmIn0=
`

**Comment by carlos12silva94** [comment]
Ok. I think i've found the main issue. 
After delete my previous version(s) i had to remove the spotify cache:
`rm -R ~/.config/spotify`

Now im not seeing ads. I'll use it a bit to make sure the audio ads are also not presented and then i close this issue

**Comment by carlos12silva94** [comment]
Also, do you know something similar to mac?

**Comment by polyzen** [comment]
@carlos12silva94. not the same concept but I just saw https://github.com/simonmeusel/MuteSpotifyAds.
