### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by evanesoteric** [abba23/spotify-adblock-linux#36]
To update this, do I want to need to overwrite the blacklist and whitelist files?
Do I need to perform another `make install`?

Also, how may I get involved should you no longer maintain this?
Tshark, null-route hosts to test, and if good add to blacklist?

**Comment by abba23** [comment]
>To update this, do I want to need to overwrite the blacklist and whitelist files?
Do I need to perform another make install?

Yes, if you make any changes, like editing the whitelist/blacklist, you'll have to run `make` / `make install` again.

>Also, how may I get involved should you no longer maintain this?

I plan to maintain this for the forseeable future and you're welcome to make pull requests if you have something useful to contribute. If you want to continue maintaining an abandoned project, you can always fork it.

>Tshark, null-route hosts to test, and if good add to blacklist?

When you run it from a terminal, it already shows you all the requests it blocks and lets through, so there shouldn't be any need for Wireshark/tshark in most cases. I personally just edit the whitelist/blacklist and run `make` for testing.

**Comment by evanesoteric** [comment]
Top work man, A+.
I appreciate this/you.
Thank you!
