### ISSUE TITLE
getaddarinfo failed

### ISSUE THREAD

**Issue by chriskoumou** [abba23/spotify-adblock-linux#4]
when running the "LD_PRELOAD=./spotify-adblock.so spotify" there is an error that says ERR: getaddrinfo failed

**Comment by abba23** [comment]
Sounds like a problem with your network configuration. For some reason DNS resolution is failing. A faulty DNS server, firewall or proxy configuration could be the reason I suppose.

**Comment by chriskoumou** [comment]
I will look, into this thank you

**Comment by chriskoumou** [comment]
Sorry again,I am an intermediate linux user and i haven't found anything searching the web.You would help me a lot if you could suggest to me more specific actions that I could take to fix this problem

**Comment by abba23** [comment]
The only code-related reason I can think of is that I recently changed the return value for blocked `getaddrinfo` calls. Although it's still working perfectly fine for me, you might want to try and build from an older commit (e.g. dbf82d6b32fac80c360ebfcd6b17c6518dd6e50e).

That error alone isn't exactly much to go on though and can apparently happen for any number of reasons. As I've never seen it myself either, I really don't know how else to help you.

**Comment by chriskoumou** [comment]
ok thank you very much

**Comment by abba23** [comment]
I've now come across this error message, too. It seems like Spotify sometimes outputs it when we block a `getaddrinfo` call. Everything is still working fine though, so we can just ignore it for now I think.
