### ISSUE TITLE
object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored

### ISSUE THREAD

**Issue by SpookyPool** [abba23/spotify-adblock-linux#41]
This is the output I'm getting:
```kevin@Kevin-Developer:~$ LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
Gtk-Message: 09:23:12.308: Failed to load module "canberra-gtk-module"
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
[0224/092312.550209:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
```
Does this mean the injection is not working?

**Comment by SpookyPool** [comment]
I got it fixed. Deleted `spotify-adblock.so`, then running `make` again. and it worked :D

**Comment by nhmanas** [comment]
deleting and running `make` again didn't work for me

**Comment by abba23** [comment]
Without knowing what you did exactly (did you delete `./spotify-adblock.so` or `/usr/local/lib/spotify-adblock.so`? Did you also run `sudo make install` again?) and if there was any output during compilation, it's hard to guess what went wrong.

Please try the following:
1. `sudo make uninstall`
2. `make clean`
3. `make`
4. `sudo make install`

If that doesn't work, you could try downloading the latest prebuilt `spotify-adblock.so` from the [releases page](https://github.com/abba23/spotify-adblock-linux/releases) and manually copying it to `/usr/local/lib`.

**Comment by nhmanas** [comment]
I forget the `make clean` it's working now. Thanks!
