### ISSUE TITLE
/bin/sh: symbol lookup error: /usr/lib/spotify-adblock.so: undefined symbol: dlerror

### ISSUE THREAD

**Issue by LinArcX** [abba23/spotify-adblock-linux#42]
I [have this issue](https://github.com/void-linux/void-packages/issues/19494) but i'm not sure is it related to void-linux or spotify-adbloc-linux. So i ask it here too.

**Comment by abba23** [comment]
Do you get the same error when manually building/installing it directly from this repo?

**Comment by LinArcX** [comment]
Surprisingly this works:
`LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify`

But [as you can see here](https://github.com/void-linux/void-packages/blob/3a5299491cbd739943d756951ff0757eb667e445/srcpkgs/spotify-adblock-linux/template#L18), I put __spotify-adblock.so__ in `usr/lib` not in `/usr/local/lib/`. I'm confused!

**Comment by abba23** [comment]
Looks like it's related to how Void Linux builds it then. There have been some changes to the Makefile in v1.1. Maybe there's something wrong with the [updated template](https://github.com/void-linux/void-packages/blob/master/srcpkgs/spotify-adblock-linux/template) (the CFLAGS definition seems to be redundant now at least).

**Comment by LinArcX** [comment]
Yeah, unfortunately someone who upgraded the application version, didn't notice(or care) to test the program against new changes. He just changed the version number and checksum and create the PR!

Anyway.. thank you so much for your help.

**Comment by LinArcX** [comment]
Ok, i tried to update template file. But seems void-linux doesn't use `/usr/local`:

https://github.com/void-linux/void-packages/blob/091ab0b612d039891f4d549f9f054567bcef3627/common/hooks/pre-pkg/99-pkglint.sh#L24

**Comment by abba23** [comment]
`/usr` is the correct location. `/usr/local` should only be used for manually installed packages that are not managed by your package manager.

**Comment by LinArcX** [comment]
So, i remove line 14-20 from template file. By default it put .so files here: __/usr/lib/spotify-adblock.so__
Also tried to use it:
```
╰ LD_PRELOAD=/usr/lib/spotify-adblock.so spotify
/bin/sh: symbol lookup error: /usr/lib/spotify-adblock.so: undefined symbol: dlerror
```
