### ISSUE TITLE
podcasts url

### ISSUE THREAD

**Issue by bjacke** [abba23/spotify-adblock-linux#43]
"traffic.megaphone.fm",
    "dcs-b.megaphone.fm",
need to be whitelisted for podcasts.

**Comment by bjacke** [comment]
also dcs.megaphone.fm - probably a wildcard for *.megaphone.fm would be helpful to have.

**Comment by abba23** [comment]
Thanks for the report! The domains have no been added to the whitelist ([commit](https://github.com/abba23/spotify-adblock-linux/commit/e5c0f25c43b78a04e334d0f0540fb79881cbcf1b)).
