### ISSUE TITLE
Spotify wont update liked songs

### ISSUE THREAD

**Issue by thespyboss** [abba23/spotify-adblock-linux#45]
On my phone and windows spotify, my liked songs will update to what i have added. On linux with using the blocker version and non-blocker version, spotify wont update the liked songs even if i have signed out and logged back in. Is there any way to fix this?

**Comment by abba23** [comment]
>On linux with using the blocker version and non-blocker version, spotify wont update the liked songs

You have the same problem when not using the adblocker?

The console output when adding a song to your liked songs would be useful to see if anything has been blocked that shouldn't be.

**Comment by thespyboss** [comment]
@abba23 It started working for some reason haha. Ill close this. Thanks for trying to help though!
