### ISSUE TITLE
Request to provide prebuilt binaries

### ISSUE THREAD

**Issue by VA-service7232** [abba23/spotify-adblock-linux#49]
Please Provide Prebuilt binaries as building from source is almost not possible in distros like solus

**Comment by P0SlX** [comment]
[Here](https://github.com/abba23/spotify-adblock-linux/files/4522613/spotify-adblock.so.tar.gz), built this morning.

**Comment by abba23** [comment]
I can't really see why building this from source would be any harder on Solus than on any other Linux distribution.

I have however now set up GitHub Actions workflows that will automatically build the project on every push and attach an artifact to every release.
