### ISSUE TITLE
Requesting future update guideline

### ISSUE THREAD

**Issue by k3VTSjczL3** [abba23/spotify-adblock-linux#51]
The script works great, for now. But when you update the whitelist or blacklist in future, how should we update the script? Please add a seperate section how to update the script.

Thank you for the amazing work!

**Comment by abba23** [comment]
You just have to build and install it again, just like you already did. I don't think this needs to be mentioned explicitly.

**Comment by k3VTSjczL3** [comment]
> You just have to build and install it again, just like you already did. I don't think this needs to be mentioned explicitly.

Yeah I'm actually thinking about a heads-up when it gets updated. Will be great if you have a twitter or reddit or something to give us a heads-up for a new version. Guess I have to check time to time. Thank you again!

**Comment by polyzen** [comment]
https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-releases-for-a-repository
and/or
https://github.com/abba23/spotify-adblock-linux/commits/master.atom
