### ISSUE TITLE
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored

### ISSUE THREAD

**Issue by mugi789** [abba23/spotify-adblock-linux#53]
why is this?

ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
No protocol specified

(spotify:7748): Gtk-WARNING **: 15:57:11.481: cannot open display: :0.0

**Comment by abba23** [comment]
It's hard to tell why this happens without knowing what you did exactly. How did you install Spotify? What commands did you run to build/install the adblocker and what were their outputs?

Are you sure you're not using the snap Spotify package (this doesn't work, as noted in the readme)? If you installed Spotify from the Ubuntu Software Center, have a look at https://github.com/abba23/spotify-adblock-linux/issues/52.
