### ISSUE TITLE
Does it work with the flatpak version?

### ISSUE THREAD

**Issue by k3VTSjczL3** [abba23/spotify-adblock-linux#55]
If I want to use it on not a Debian based distro will it work?

**Comment by abba23** [comment]
It will *probably* not work with Flatpak for the same reason that it doesn't work with the Snap. The library file won't be available inside the container and thus can't be preloaded.

It's definitely possible to use it on non-Debian based distributions though. I'm using it on Arch Linux for example. Looking at the [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=spotify), it seems like it just unpacks the `.deb` package and copies the Spotify binary and other files to their appropriate locations. You should be able to just do that manually on whatever distribution you're using.

**Comment by k3VTSjczL3** [comment]
ok thanks!

**Comment by rany0** [comment]
It's actually possible to use this with flatpak!

You have to create the following file with the path `~/.local/share/flatpak/overrides/com.spotify.Client`. It must contain:
```
[Context]
filesystems=~/Documents/code/misc/spotify-adblock-linux

[Environment]
LD_PRELOAD=/home/rany/Documents/code/misc/spotify-adblock-linux/spotify-adblock.so

```
(here `~/Documents/code/misc/spotify-adblock-linux` is where I stored this repo and LD_RELOAD is self-explanatory)

and that's it!

**Comment by rany0** [comment]
I find flatpak to be much more flexible than snaps.

**Comment by rany0** [comment]
Update: this doesn't seem to work anymore on the latest flatpak version. Oh well....

**Comment by tandy-1000** [comment]
damn.. i was just about to do that. any update on trying to make this work @abba23 ?

**Comment by Uonio** [comment]
This can also be done via `flatpak override`
```
sudo flatpak override --filesystem=~/spotify-adblock-linux com.spotify.Client
sudo flatpak override --env=LD_PRELOAD=~/spotify-adblock-linux/spotify-adblock.so com.spotify.Client
```
@tandy-1000  I hope this helps

**Comment by AloisJanicek** [comment]
The error when running spotify-adblock with flatpak suggests that it could be en issue with [CEF](https://bitbucket.org/chromiumembedded/cef/src) (or at least that's what I thought)
```
bwrap: symbol lookup error: /usr/lib/spotify-adblock.so: undefined symbol: cef_string_userfree_utf16_free
```
I tried to build spotify-adblock-linux with CEF which version corresponds to version which my flatpak spotify actually uses but it didn't help.

In case someone more skillful is willing to look more deeply into this
[here](https://www.spotify.com/ps-en/opensource/) [spotify.com] is a list which maps spotify versions to CEF versions
[here](https://cef-builds.spotifycdn.com/index.html#linux64) [spotifycdn.com] you can find and download corresponding CEF version
