### ISSUE TITLE
Don't block audio ads

### ISSUE THREAD

**Issue by xRealNeon** [abba23/spotify-adblock-linux#60]
Hey is used your app but it only blocks the visual ads

**Comment by abba23** [comment]
It's really hard to identify the problem without any information other than that it doesn't work.

* How did you compile and install it?
* Were there any errors during compilation or installation?
* How did you install Spotify (Ubuntu Software Center, Debian package, snap, ...)?
* What command did you run Spotify with?
* What was the terminal output?

**Comment by Raudonkepuris** [comment]
Today, digster audio/banner ads started playing in my AUR [spotify-adblock-git](https://aur.archlinux.org/packages/spotify-adblock-git/) [spotify](https://aur.archlinux.org/packages/spotify/) install, I've just recompiled it from github so far - nothing.

**Comment by xRealNeon** [comment]
I'm not at my PC right now I'll recompile it tomorrow and try again I'll write if there are any errors.

**Comment by xRealNeon** [comment]
I get this Error ![](https://i.imgur.com/EQEMsVH.png)

**Comment by xRealNeon** [comment]
I am running Spotify 1.1.26.501.gbe11e53b on Kubuntu 19.10 and i got Spotify from the Kubuntu store

**Comment by abba23** [comment]
>ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored

Please have a look at https://github.com/abba23/spotify-adblock-linux/issues/41.

**Comment by xRealNeon** [comment]
No errors but Ad banner on the startpage ill report back if i get audio ads

**Comment by xRealNeon** [comment]
I also got audio ads without errors

**Comment by abba23** [comment]
Is there any terminal output at all?

I am using version `1.1.10.546.ge08ef575` ([which seems to be the current stable version](https://repository.spotify.com/dists/stable/non-free/binary-amd64/Packages)), but just tested version `1.1.26.501.gbe11e53b` and it appears to work fine without any banner or audio ads for me too.

**Comment by xRealNeon** [comment]
No terminal output at all

**Comment by xRealNeon** [comment]
I think the Kubuntu store installs the snap version I installed the debian package version and it seems to work
