### ISSUE TITLE
make compilation error

### ISSUE THREAD

**Issue by badlydrawnface** [abba23/spotify-adblock-linux#61]
How do I fix this. I am on Mint 20, Spotify (non-fp) from the Mint Store.

In file included from /usr/include/x86_64-linux-gnu/curl/curl.h:38,
                 from spotify-adblock.c:3:
/usr/include/x86_64-linux-gnu/curl/system.h:430:12: fatal error: sys/types.h: No such file or directory
  430 | #  include <sys/types.h>
      |            ^~~~~~~~~~~~~
compilation terminated.

**Comment by abba23** [comment]
>`error: sys/types.h: No such file or directory`

Looks like you're missing libc headers. Installing `libc6-dev` should fix that. Next time please try pasting error messages into a search engine of your choice before creating an issue.

**Comment by badlydrawnface** [comment]
It worked. Thank you
