### ISSUE TITLE
Failed to load Module

### ISSUE THREAD

**Issue by jackthiago** [abba23/spotify-adblock-linux#62]
when i try to lauch, gives me the error that 3 modules can't load

![terminale](https://user-images.githubusercontent.com/69475738/90243423-28596d80-de2f-11ea-9c3b-d187a6a3f4c2.png)

**Comment by abba23** [comment]
Those `Gtk-Message` lines are unrelated. You should however see a log of blocked and unblocked connections in the terminal. If not, please make sure you aren't using the Spotify snap package (see https://github.com/abba23/spotify-adblock-linux/issues/52).

**Comment by jackthiago** [comment]
yes i was using the snap, now i resolve that. but when launching i still got this error buffer manager:
(i already tried to delete spotify-adblock.so and tried to rerun make install but it doesn't change)

![terminale1](https://user-images.githubusercontent.com/69475738/90247183-5e4e2000-de36-11ea-85ca-66c1149e1306.png)

**Comment by abba23** [comment]
That error is also unrelated (you'll get the same error when launching Spotify without the adblocker) and doesn't matter. Looks like the adblocker is working now though.

**Comment by jackthiago** [comment]
Yes, it working perfectly. Thanks :)
