### ISSUE TITLE
Email account is not recognized day by day

### ISSUE THREAD

**Issue by GiwrgosTerezakis** [abba23/spotify-adblock-linux#63]
Every day i have to make new email account to get it working

**Comment by abba23** [comment]
Can you explain your problem in more detail? What are you trying to do? Which part of that isn't working?

**Comment by GiwrgosTerezakis** [comment]
Yes, every new day i have to create new email account to use with the app  because it throws me an error that the username or the password is incorrect. I guess they ban the account. I've tried to both verify my email and not for the service but neither worked.

**Comment by abba23** [comment]
That's almost certainly unrelated to this adblocker. Looking at https://github.com/abba23/spotify-adblock-linux/issues/18, my guess would be that it happens, because you're connecting to Spotify through Tor or a shared proxy/VPN.
