### ISSUE TITLE
Adblocking broken in Spotify 1.1.42.622

### ISSUE THREAD

**Issue by abba23** [abba23/spotify-adblock-linux#65]
Spotify version 1.1.42.622 seems to be making some ad requests through CEF (Chromium Embedded Framework) instead of *libcurl* as before, bypassing the current function hooks.

**Comment by coxackie** [comment]
hmmm... I have been using 1.1.42.622 on arch linux for some days now with adblock and have not noticed any ads. I will continue testing and update.

**Comment by realnc** [comment]
I do get ads on 1.1.42.622. There's also an empty block in the UI where normally an ad appears. Nothing is printed on the terminal when ads are played, suggesting the ads are not fetched through libcurl.

Looks like the LD_PRELOAD way of blocking ads might not be possible anymore going forwards.

**Comment by abba23** [comment]
>Looks like the LD_PRELOAD way of blocking ads might not be possible anymore going forwards.

Why not? *libcef* is just another library with functions that we can intercept.

**Comment by realnc** [comment]
> Why not? _libcef_ is just another library with functions that we can intercept.

Oh, it's shipped as a dynamic library. I had the impression everything was statically linked.

**Comment by coxackie** [comment]
hmm... maybe I do not get those ads because I am using adguard dns.

**Comment by abba23** [comment]
I just tested blocking the ads in the new version by hooking `cef_urlrequest_create`, which seems to work. It requires the CEF headers to compile though.

**Comment by abba23** [comment]
I've now pushed a new branch with my changes. If you can, please try it out and report back if there are any problems.

**Comment by realnc** [comment]
Just built it. Works fine. The empty ad block is gone. Haven't heard any ads yet.

**Comment by coxackie** [comment]
Realising I am not to be very much trusted on my input. As I use (on router) adguard DNS, even when I run spotify without abblock I do not get any ads. I will keep running for a little while without adblock; I would not imagine adguard blocks everything spotify-related though...

**Comment by realnc** [comment]
Do you get things like the following, like I do?

    [-] cef_urlrequest_create:      https://spclient.wg.spotify.com/ads/v1/ads/leaderboard?payload=...

**Comment by trespordez** [comment]
Sometimes, Spotify plays some audio ads (on both 1.1.42 and 0.9.17) for me too.

**Comment by coxackie** [comment]
I also think (like @realnc) that, if legal, the headers should be probably added to this repo, as otherwise it is a quite large download.

**Comment by d0m1n1q0** [comment]
It works on first instance only.
Consecutive launches crash. Tried it on debian stretch & buster.
Same pattern after reboot.

**Comment by abba23** [comment]
> Sometimes, Spotify plays some audio ads (on both 1.1.42 and 0.9.17) for me too.

Is this with the new branch? Is there any output in the terminal? I'm not sure how version 0.9.17 is relevant. Isn't that one like five years old at this point?

> if legal, the headers should be probably added to this repo, as otherwise it is a quite large download.

I'm a bit on the fence about this. I *think* CEF's BSD license is compatible with the GPL, so it should be possible from a legal perspective and it would certainly be more convenient for building. On the other hand, it would add a huge amount of external code, that might have to be kept up to date and most of which isn't actually used. Maybe a compromise would be only adding the headers/symbols that are actually needed. I'd prefer a way to just download the headers from the original repository without all the stuff we don't need though.

> It works on first instance only. Consecutive launches crash.

You're launching one instance, closing it and then launching a second one that crashes? Is there any output in the terminal? Have you tried deleting Spotify's config (`~/.config/spotify`) and cache (`~/.cache/spotify`)?

**Comment by d0m1n1q0** [comment]
@abba23 
Yeah. Launching one instance works fine and the second one crashes.
No output in journalctl -p 3 -xb. Tell me me what you would care to look for.
Yes I had deleted both configs. No good. Deleted again. Same behavior.

**Comment by trancef0rmer** [comment]
I have master installed from AUR. It created the socket file under /usr/lib and a .desktop file under ~/.cache/yay/spotify-adblock-git. So far so good until I updated spotify up to 1.1.42.622. Then I built this branch and it created the socket file under /usr/local/lib. I have updated the socket path in that .desktop file and it works only if I double click the .desktop file from it's directory. 
![folder](https://imgur.com/sTvwyLa.png)
If I start it from the menu (cinnamon) it's not working
![menu](https://imgur.com/uzcmizb.png)
Also, copied the new .so over the old .so and the result is the same.
I am sure I miss something.
Overall, the fix is working and should go to master branch.
Thanks.

**Comment by abba23** [comment]
@d0m1n1q0 
I meant Spotify's output when you launch it from a terminal.
This only happens when you launch Spotify with the adblocker and did not happen with the old Spotify version and old adblocker version? Does it also crash when you launch the old Spotify version with the updated adblocker or the new Spotify version with the old adblocker?

---

@trancef0rmer 
>socket file

`.so` is short for *shared object*, not *socket*

>.desktop file under ~/.cache/yay/spotify-adblock-git

That's just your AUR helper's cache directory. The actual `.desktop` file you'd have to modify (or rather override by creating a new modified one in `~/.local/share/applications`) is in `/usr/share/applications`.

**Comment by alsoGAMER** [comment]
Same issues here, every time I open Spotify it crashes immediately.
To make it kinda working, I've to delete the cache directory and kill any Spotify child process, then try to start the client, and if it crashes, repeat the latter for about 4/5 times, and sometimes starts up...
And it only starts when launched using the terminal, otherwise, it just keeps crashing, no matter what I do.

Here a recurrent error:
```
spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)
Gtk-Message: 01:30:40.789: Failed to load module "appmenu-gtk-module"
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[+] cef_urlrequest_create:      https://login5.spotify.com/v3/login
[1002/013042.424191:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
zsh: trace trap (core dumped)  LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify %U
```

Sometimes instead it starts up and began making normal requests to its servers, but the window is just pitch black, it doesn't load anything in the client, seems that the graphical process randomly dies, but the system hook process and the networking process still working fine.

Env infos:
Spotify version: 1.1.42.622
Adblocker branch: cef_urlrequest_create

**Comment by d0m1n1q0** [comment]
@abba23 
The output after launching a second instance of adblock LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify is:

[1002/031048.880380:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap

And the output after launching spotify from command line for the second time is :

[1002/031622.518995:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap

Previous version of spotify and adblocker had no issues.

**Comment by alsoGAMER** [comment]
> Previous version of spotify and adblocker had no issues.

Same here

**Comment by trespordez** [comment]
> Is this with the new branch? Is there any output in the terminal? I'm not sure how version 0.9.17 is relevant. Isn't that one like five years old at this point?

I still use this version because it's less resource heavy (i have a shitty pc). Also, the newer versions used to crash very often.

**Comment by kaizoku49** [comment]
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
I'm getting these errors. The spotify works but audio and video ads show up + banners as well. What am I doing wrong ?

**Comment by abba23** [comment]
>I come to think this is an issue of spotify-client and not the adblocker.

@alsoGAMER
Can you confirm that? Does it also crash when you launch the new Spotify version without adblocker?

---

@trespordez
I'm sorry, but this issue is about version 1.1.42.622. You testing the new version would probably not be very helpful if it already crashes for you without adblocking.

**Comment by d0m1n1q0** [comment]
@abba23 
I confirm that rolling back to Spotify version 1.1.26.501 works as expected with no issues regardless of launching spotify or adblocker.
It all malfunctions once 1.1.42.622 is installed. At least in debian. I might give it a shot during the weekend in arch although I can't see why it would behave differently.

I'll stick to 1.1.26.501 for a while.

Let me know if you need to run any other tests.

**Comment by JPUnD** [comment]
I've came here just to confirm that running `spotify-adblock-linux` in Manjaro from the AUR does seem to encounter issues with the latest version of Spotify. 
I've reinstalled and cleaned all local files, when trying to login from the `spotify-adblock-linux` it kept giving me a warning that my firewall was blocking Spotify or something like that.
Now trying to play songs with Spotify works but with `spotify-adblock-linux` doesn't, it play a little bit in the beginning (~ 5 seconds) and then stops saying "Can't play the current song".

**Comment by akinhet** [comment]
@JPUnD 
I had the same issue. Though it seems that `spotify-adblock-git` is working, but only blocks visual ads and not ones that play in between songs, which is still better than not functioning at all. They both reference this repo, but `spotify-adblock-linux` is outdated I think.

**Comment by Syzygianinfern0** [comment]
I can confirm too. Ads between songs are active on Arch Linux and on Pop OS with the latest version of spotify and spotify-adblock-linux built from source.

**Comment by realnc** [comment]
AUR almost certainly tracks the git master branch. Not the cef_urlrequest_create branch which is the one that can block ads in 1.1.42.

**Comment by saputpoleng** [comment]
> @abba23
> I confirm that rolling back to Spotify version 1.1.26.501 works as expected with no issues regardless of launching spotify or adblocker.
> It all malfunctions once 1.1.42.622 is installed. At least in debian. I might give it a shot during the weekend in arch although I can't see why it would behave differently.
> 
> I'll stick to 1.1.26.501 for a while.
> 
> Let me know if you need to run any other tests.

how do i get the previous version (1.1.26.501) ?,
currently installed on my computer is version 1.1.42.622 and adblock not working

**Comment by abba23** [comment]
To summarize, the `cef_urlrequest_create` branch generally seems to work. While there were some problems reported, it's not quite clear if they are related to the adblocker itself or just the new Spotify version.

In order to preempt any more complaints about the adblocker not working with the new Spotify version, I plan to just merge the branch into master for now and address any problems in separate issues.

A concern with this update are the CEF headers, which are now needed for building. I'd like to try and find a better solution than downloading the whole CEF build, preferably one that doesn't involve adding ten thousands lines of code to this repo, but this effort can also be tracked in a separate issue.

**Comment by alsoGAMER** [comment]
@abba23 
> Can you confirm that? Does it also crash when you launch the new Spotify version without adblocker?

Yes, it crashes with the same error:
`[1002/151639.740140:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
`

I've also noticed that when I ctrl-c on the terminal to quit spotify, this comes out:
`^Czsh: segmentation fault (core dumped)  LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify %U
`

**Comment by akinhet** [comment]
It turns out that `spotify-adblock-git` on AUR had an update a few hours ago and now it seems to work. I'm not sure why though.

**Comment by trespordez** [comment]
It's working perfectly with the latest version, on Lubuntu 16.04. Just make sure you're logged in before running the adblock.
