### ISSUE TITLE
Song doesn't play in arch linux

### ISSUE THREAD

**Issue by itsshreyarora** [abba23/spotify-adblock-linux#73]
I used the https://aur.archlinux.org/packages/spotify-adblock-linux package with the  spotify-dev package, and songs dont play, or sometimes play for a few seconds before stopping.

**Comment by abba23** [comment]
Try the `spotify-adblock-git` AUR package, which packages the latest commit instead of the latest release. If that doesn't work, I'll need the terminal output to see what's going on.

**Comment by isaacimran** [comment]
spotify-adblock-git is working fine for me, spotify-adblock-linux is not playing the songs just like @itsshreyarora .(OS: Arch Linux)

**Comment by itsshreyarora** [comment]
Thanks for the quick replies, but sadly,  the `spotify-adblock-git` package could not install. here is the entire thing
```Preparing...
Cloning spotify-adblock-git build files...
Checking spotify-adblock-git dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building spotify-adblock-git...
==> Making package: spotify-adblock-git r68.624fad4-1 (Mon 05 Oct 2020 02:46:21 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating spotify-adblock git repo...
Fetching origin
  -> Downloading cef.tar.bz2...
** Resuming transfer from byte position 262914598
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0    49    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 416
==> ERROR: Failure while downloading http://opensource.spotify.com/cefbuilds/cef_binary_80.0.8%2Bgf96cd1d%2Bchromium-80.0.3987.132_linux64_minimal.tar.bz2
    Aborting...
Failed to build spotify-adblock-git```

I checked the url by using my browser, and did not get an error then.

**Comment by itsshreyarora** [comment]
Update: running `yay -S spotify-adblock-git` worked, so it seems like the problem was with the gui i was using.  And, as @isaacimran said, its working now. 
Thank you for all help!

**Comment by polyzen** [comment]
A new release would be appreciated so as to get the stable package working.
