### ISSUE TITLE
Spotify adblock opens separate Spotify instance when pinned to dock/taskbar

### ISSUE THREAD

**Issue by fighuass** [abba23/spotify-adblock-linux#77]
When I try to pin a .desktop file (the one mentioned in the main page) and open it in my dock/taskbar, it opens a separate instance (the original Spotify), which is annoying. How do I make it so that it doesn't launch a separate instance and only opens the .desktop file?

I mean, right now it goes like [https://i.imgur.com/IpXii0v.png](this), where the left is Spotify adblock and the right is the original Spotify.

**Comment by fighuass** [comment]
Managed to fix it somehow, not sure why, but I initially added it as a shortcut in the KDE app menu (env LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify %U), then changed it to "/usr/local/lib/spotify-adblock.so" and saved it. Launching did nothing so I changed it back, and then it was fixed all of a sudden.

**Comment by akash-258** [comment]
That did not work for me in manjaro cinnamon. Please reopen this issue.
