### ISSUE TITLE
spotify: symbol lookup error: /usr/local/lib/spotify-adblock.so: undefined symbol: dlsym

### ISSUE THREAD

**Issue by jaakdentrekhaak** [abba23/spotify-adblock-linux#78]
After doing the installation as specified in the README.md file, when I try to run `LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify`, I get the following error:
`spotify: symbol lookup error: /usr/local/lib/spotify-adblock.so: undefined symbol: dlsym`

(There where no errors during the installation itself)

I don't know what to do, I spent half an hour searching on the internet, but without success.

**Comment by OancaAndrei** [comment]
Hi, I had your same issue and, after some time, I realized that I was trying to patch the Snap version of Spotify.
So make sure that you installed the `deb` version.

**Comment by jaakdentrekhaak** [comment]
Totally forgot I installed the snap version. It seems to be working right now. Thank you very much @OancaAndrei
