### ISSUE TITLE
Latest spotify doesnt work 

### ISSUE THREAD

**Issue by Endeavour821** [abba23/spotify-adblock-linux#79]
can u make the addblock work again on this latest version? cz i cant roll back to older version :( thanks 
![2020-10-16-222717_1366x768_scrot](https://user-images.githubusercontent.com/71737156/96277775-e8fdf780-0ffe-11eb-8c81-ee8b100e534d.png)

**Comment by abba23** [comment]
The latest adblocker version should already work with the latest Spotify version. There's probably something else wrong. What's the terminal output when you launch Spotify with the adblocker?

**Comment by torshin** [comment]
![DeepinScreenshot_select-area_20201019130349](https://user-images.githubusercontent.com/11928479/96430994-92193d80-120b-11eb-8645-c8a630d13b61.png)
I have same issue. This is my terminal output.

**Comment by abba23** [comment]
@torshin `cannot open shared object file` likely means that the path to `spotify-adblock.so` that you specified is wrong. It looks like you might be missing the **s** in `Downloads`.

**Comment by torshin** [comment]
@abba23 oh what a shame🤦🏼‍♂️. But i really had the issue. Will make a screenshot, if it occurs again.

**Comment by torshin** [comment]
Everything works perfect with last script and last spotify. Thanks @abba23!

**Comment by muametgrooby** [comment]
Looks like it is not working
![image](https://user-images.githubusercontent.com/42146933/96747711-e61d5100-13c8-11eb-8894-36c72aef4046.png)

**Comment by flleeppyy** [comment]
yeeaahhh i just got 5 ads in a row. There is no popup or banner ads, just audio ads

**Comment by Endeavour821** [comment]
![2020-10-24-080114_1366x768_scrot](https://user-images.githubusercontent.com/71737156/97064303-1c2c2200-15cf-11eb-8d03-803942b9b21f.png)
dude why it closed , in my spotify still doesnt work

**Comment by abba23** [comment]
@muametgrooby @Endeavour821:
Both of you aren't using the latest adblocker version.

@flleeppyy:
I can't tell for sure what's wrong just from that, but please also make sure you're using the latest adblocker version.

**Comment by flleeppyy** [comment]
I've re-downloaded it multiple times, im 99.9% sure i have the latest version, and its still not working
