### ISSUE TITLE
Second time fails to start

### ISSUE THREAD

**Issue by d0m1n1q0** [abba23/spotify-adblock-linux#80]
Hi
On debian first time issuing LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify works fine with no issues.

Closing spotify and launching again with same command does not start and output is following:
------------------------------
[1022/100636.700176:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap.
------------------------------
I keep clearing .cache and .config files but situation of crashing remains.
Any suggestions?

**Comment by abba23** [comment]
That problem was already reported [here](https://github.com/abba23/spotify-adblock-linux/issues/65), but seems to be related to the new Spotify version, not the adblocker, because it also happens when you launch Spotify without the adblocker.

**Comment by d0m1n1q0** [comment]
Thank you for the reply.
Yes, you are correct, it happens also by issuing spotify (just tried it).
Funny thing this occurs in debian(buster), I had no problems with arch on same box.
Anyways thanks again for the effort. I will shift to the previous versions.
You might want to close it.
