### ISSUE TITLE
pip wget ssh and curl failed creating connection with DNS problem

### ISSUE THREAD

**Issue by numeropi** [abba23/spotify-adblock-linux#82]
Hi, I add this here in order to help others to find the solution to what it happened to me during the last days after doing "sudo make install" , I don't know how it happened but I have spent many hours trying to figure out what my linux was not working till I did sudo make unisntall and everything went fine to normal.

I started to notice that ssh anyserver responded like a DNS problem connection, but DNS where working fine with a ping or nslookup. 

ex: ssh anyserver
`ssh: Could not resolve hostname aisha: Non-recoverable failure in name resolution
`

```
wget  -4 http://pypi.org/simple/flask-bcrypt/ -vv
--2020-10-27 14:35:54--  http://pypi.org/simple/flask-bcrypt/
Resolviendo pypi.org (pypi.org)... [-] pypi.org
falló: Fallo irrecuperable en la resolución del nombre.
wget: no se pudo resolver la dirección del equipo “pypi.org”
```
----------------------

PIP also was failing: 
```
pip install pyexcel_ods
[-] pypi.org
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa6e266d430>: Failed to establish a new connection: [Errno -4] Fallo irrecuperable en la resolución del nombre')': /simple/pyexcel-ods/
```
 
I was getting crazy because I though it was a problem of systemd-resolve, DNS, proxies, etc etc. but finally doing a sudo make uninstall on the spotify-adblock-linux solved the problem. I am not sure if you could fix it for next versions? 

Thanks

**Comment by abba23** [comment]
`make install` just copies the `spotify-adblock.so` file to `/usr/local/lib`. It doesn't get loaded and thus can't affect anything unless you explicitly load it using `LD_PRELOAD`.

The only explanation I can think of is that you set `LD_PRELOAD=/usr/local/lib/spotify-adblock.so` somewhere globally (e.g.  `/etc/profile`, `~/.bashrc` or `~/.bash_profile`) or exported it in your shell and forgot about it.

**Comment by numeropi** [comment]
Sorry, then yes, it was that, I did added in .bashrc and forgot about it, I removed that before doing the make uninstall!!
LD_PRELOAD=/usr/local/lib/spotify-adblock.so

Thanks.
