### ISSUE TITLE
Suggestion Not Issue (Not sure where I should put it...)

### ISSUE THREAD

**Issue by JacobHornbeck** [abba23/spotify-adblock-linux#83]
Hello,

I really enjoy this program! It blocks all the ads (banner, audio, and video) for me...
I didn't know where I was supposed to put suggestions... so I just put it here:
I really like this for Linux, but I would really like one for Windows... how hard would it be to modify this code to make it work on Windows?

Thanks!

**Comment by abba23** [comment]
[BlockTheSpot](https://github.com/mrpond/BlockTheSpot) might be what you're looking for.

**Comment by JacobHornbeck** [comment]
@abba23 I believe that is what I am looking for, thank you! I had searched for something like that, but I didn't see that one...
