### ISSUE TITLE
wget -O cef.tar.bz2 does not work anymore

### ISSUE THREAD

**Issue by elbc56** [abba23/spotify-adblock-linux#85]
Following the procedure step by step with the "how to", I've noticed that this step failed : 

wget -O cef.tar.bz2 http://opensource.spotify.com/cefbuilds/cef_binary_80.0.8%2Bgf96cd1d%2Bchromium-80.0.3987.132_linux64_minimal.tar.bz2

**Comment by aleksandrs-ledovskis** [comment]
Works for me

```
$ wget http://opensource.spotify.com/cefbuilds/cef_binary_80.0.8%2Bgf96cd1d%2Bchromium-80.0.3987.132_linux64_minimal.tar.bz2 | head -n1
Resolving opensource.spotify.com (opensource.spotify.com)... 54.230.228.187, 54.230.228.161, 54.230.228.76, ...
Connecting to opensource.spotify.com (opensource.spotify.com)|54.230.228.187|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 262914598 (251M) [application/x-tar]
```

SHA-256 hashsum of file is "8980a0d5d2b7004c90bb9e07711afe2b5b5993f027bc8e8ee73a805652f7ed4f"

**Comment by elbc56** [comment]
Ok, so it is not an issue. I've been trying from different post stations and same result, I don't understand. Sorry for opening this wrong issue.

**Comment by elbc56** [comment]
Sorry bu after reading again your comment I think I wasn't clear : The command works but I cannot download the entire archive, it fails at 99%. Did you successfully download without any error ? Here is what I saw (in french) :
 
cef.tar.bz2          99%[==================> ] 250,73M  6,94MB/s    ds 40s     

2020-11-27 17:05:31 (6,25 MB/s) — Fermeture de la connexion à l’octet 262913378. Nouvel essai.

--2020-11-27 17:05:32--  (essai :  2)  http://opensource.spotify.com/cefbuilds/cef_binary_80.0.8%2Bgf96cd1d%2Bchromium-80.0.3987.132_linux64_minimal.tar.bz2
Connexion à opensource.spotify.com (opensource.spotify.com)|99.86.88.89|:80… connecté.
requête HTTP transmise, en attente de la réponse… 307 Temporary Redirect
Emplacement : http://10.52.254.250/UserCheck/PortalMain?IID=7FE7634F-5E1B-0FF9-A49B-E8E3F3E53107&origUrl=aHR0cDovL29wZW5zb3VyY2Uuc3BvdGlmeS5jb20vY2VmYnVpbGRzL2NlZl9iaW5hcnlfODAuMC44K2dmOTZjZDFkK2Nocm9taXVtLTgwLjAuMzk4Ny4xMzJfbGludXg2NF9taW5pbWFsLnRhci5iejI [suivant]
--2020-11-27 17:05:32--  http://10.52.254.250/UserCheck/PortalMain?IID=7FE7634F-5E1B-0FF9-A49B-E8E3F3E53107&origUrl=aHR0cDovL29wZW5zb3VyY2Uuc3BvdGlmeS5jb20vY2VmYnVpbGRzL2NlZl9iaW5hcnlfODAuMC44K2dmOTZjZDFkK2Nocm9taXVtLTgwLjAuMzk4Ny4xMzJfbGludXg2NF9taW5pbWFsLnRhci5iejI
Connexion à 10.52.254.250:80… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : non indiqué [text/html]
Sauvegarde en : « cef.tar.bz2 »

**Comment by aleksandrs-ledovskis** [comment]
The weird `/UserCheck/PortalMain` redirect you have is due to some kind of corporate/AP middlebox.
It will probably happen for any file you download/is not specifc to this project.
