### ISSUE TITLE
clang: error: cannot specify -o when generating multiple output files

### ISSUE THREAD

**Issue by ForceGT** [abba23/spotify-adblock-linux#89]
![image](https://user-images.githubusercontent.com/31688051/103363409-07916c00-4ae1-11eb-99fe-cf851842db58.png)

Here is a screenshot from MacOS Catalina

**Comment by abba23** [comment]
This adblocker is for Linux (as implied by its name and mentioned in the description), not MacOS. You might want to have a look at [this fork](https://github.com/Dark-Matter7232/spotify-adblock-mac) though.

Note that the readme there states:
>This program requires gcc and will not compile with clang or the default macos gcc.

**Comment by ForceGT** [comment]
Do you have any idea how I'll be able to change the default gcc that comes with macos?

**Comment by abba23** [comment]
I'm sorry, but this isn't quite the right place for questions about MacOS. I'm sure however, that the answer will be easy to find using an internet search engine of your choice.
