### ISSUE TITLE
auto run script.

### ISSUE THREAD

**Issue by AllyPallies** [abba23/spotify-adblock-linux#9]
Hi there im having some issues with my autorun script and wanted to see if you can give some pointers on whats going on or how to fix them? 

Here is what i have so far
#!/bin/bash
LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify
any help would be wonderful thank you again for everything!

**Comment by tgw314** [comment]
I'm using a desktop entry like this without using a shell script
```
[Desktop Entry]
Type=Application
Name=Adblocked Spotify
GenericName=Music Player
Icon=spotify-client
TryExec=spotify
Exec=env LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify %U
Terminal=false
MimeType=x-scheme-handler/spotify;
Categories=Audio;Music;Player;AudioVideo;
StartupWMClass=spotify
```
I wish you good luck from Japan :)

**Comment by tgw314** [comment]
/home/[usename]/.config/autostart
I think it will automatically start if you put it here

**Comment by AllyPallies** [comment]
I have KDE and it’s not working. I’ve tried all I know of for it to work with no luck at all.

**Comment by tgw314** [comment]
https://wiki.archlinux.org/index.php/KDE#Autostart
I think this will be helpful

**Comment by AllyPallies** [comment]
Yea I’ve read that and still doesn’t help the preload issue, I’ve also LS’d the file and it doesn’t exist either. I don’t understand but if you look at my original post you’ll see I’ve already done everything that site told you to do. So I’m a little confused why you posted a link without looking at what I’ve done already.

**Comment by tgw314** [comment]
Does changing the permissions on the list of things you have done?

**Comment by AllyPallies** [comment]
Yep. I’ve done all that also made it  executable. Chmod the file as well. No luck.

**Comment by tgw314** [comment]
There seems to be nothing I can do other than recommend Budgie Desktop.
Sorry for not helping you.

**Comment by abba23** [comment]
>I’ve also LS’d the file and it doesn’t exist

How did you install it?
* If you did it manually, as described in the readme, then `/usr/local/lib/spotify-adblock.so` is the correct path. Make sure you actually ran `make install` (with eleveated privileges), not just `make`.
* If you used the AUR package, then the path is `/usr/lib/spotify-adblock.so` (no `local`!) instead, because that's where libraries that are managed by the package manager belong.

**Comment by AllyPallies** [comment]
I did a file lookup and the app couldn’t find it.

**Comment by abba23** [comment]
So you're saying the file is in neither of those locations? It seems the problem is a failed installation then, rather than a mistake in your autorun script.

Again, how exactly did you install it? Did you run the commands exactly as they are in the readme? Were there any error messages?

**Comment by AllyPallies** [comment]
If I load the load command in a terminal it works perfectly as I’ve saod before In my first post. So therefor it’s installed correctly. Also installed via AUR pacman.

**Comment by abba23** [comment]
>If I load the load command in a terminal it works perfectly as I’ve saod before In my first post

You didn't say that in your first post. You really just posted your one-liner script and stated that you're "having some issues" with it.

>installed via AUR pacman

Then the file should be at `/usr/lib/spotify-adblock.so`, as I said above. Is it there? Does it work if you change the path in your script accordingly?

**Comment by AllyPallies** [comment]
Negative, I’ve tried both ways without any luck at all. If I load it via the normal command in thermal is works flawlessly but my auto run script keeps failing. Also I’ve noticed once and a while adds are coming threw. How’s that possible?

**Comment by abba23** [comment]
>If I load it via the normal command in thermal is works flawlessly
>I’ve noticed once and a while adds are coming threw

So it isn't actually working flawlessly?

>How’s that possible?

It isn't. Again, did you verify that the file is actually there? Can you try reinstalling it both through the AUR and manually (as described in the readme), and test both paths in your script again?

For what it's worth, I just ran your script and it's working fine for me. The problem must be somewhere on your end.
