### ISSUE TITLE
Create an install script for distros / Linux MInt update

### ISSUE THREAD

**Issue by zastrixarundell** [abba23/spotify-adblock-linux#93]
First I gotta say that this works like a charm on most systems I've used it. Ubuntu and Manjaro worked well wiyhout any hiccups. 

I've tried using this on Linux Mint and after some time I realized that I need to install `libc6-dev`.

I can help creating a shell script which will install everything required for Debian and Arch based distros.

**Comment by abba23** [comment]
I don't think install scripts for specific distributions are necessary to be honest. The installation is simple enough and this would add more maintenance work. For Arch Linux there are also AUR packages already. If the `libc` headers aren't available by default on some distributions, I can add them to the build prerequisites.

**Comment by zastrixarundell** [comment]
Understandable. I guess just adding `libc6-dev` is adequate enough.
