### ISSUE TITLE
unable to get files using wget 

### ISSUE THREAD

**Issue by abhisheknclt** [abba23/spotify-adblock-linux#95]
when i tried this step 

 wget -O cef.tar.bz2 http://opensource.spotify.com/cefbuilds/cef_binary_80.0.8%2Bgf96cd1d%2Bchromium-80.0.3987.132_linux64_minimal.tar.bz2

it gave me an error 

 --2021-01-26 23:33:44--  http://opensource.spotify.com/cefbuilds/cef_binary_80.0.8%2Bgf96cd1d%2Bchromium-80.0.3987.132_linux64_minimal.tar.bz2
Resolving opensource.spotify.com (opensource.spotify.com)... failed: Name or service not known.
wget: unable to resolve host address ‘opensource.spotify.com’

my network connection is working fine btw

**Comment by abba23** [comment]
Looks like the site is down at the moment. Just try again later.

**Comment by abhisheknclt** [comment]
> Looks like the site is down at the moment. Just try again later.

Ok man

**Comment by roddhjav** [comment]
They have changed the domain name. It is now on https://cef-builds.spotifycdn.com/index.html The Readme should be updated accordingly.

**Comment by abba23** [comment]
Thanks for the heads-up @roddhjav! I've updated the URLs.
