### ISSUE TITLE
Can't play joe Rogan podcast

### ISSUE THREAD

**Issue by jackthiago** [abba23/spotify-adblock-linux#96]
Hi, i've found a problem trying listening to the Joe Rogan Experience.
IT says: " Spotify can't play this right now"

**Comment by abba23** [comment]
This is most likely related to some podcast hosting platform being blocked. If you provide the terminal output when trying to play the podcast, we should be able to find out which one it is and add it to the whitelist.

**Comment by jackthiago** [comment]
I believe these are the lines

 [+] cef_urlrequest_create:	https://spclient.wg.spotify.com/padme/v2/metadata/manifestId/9b2bdef2f50a510d8d2db6e8114bd4b3
[-] cef_urlrequest_create:	https://spclient.wg.spotify.com/gabo-receiver-service/v3/events/
[+] cef_urlrequest_create:	https://spclient.wg.spotify.com/extended-metadata/v0/extended-metadata
[+] cef_urlrequest_create:	https://i.scdn.co/image/5cc6f332dc3836b49f678e52631bd842b7ef4cf
[+] getaddrinfo:		i.scdn.co
[+] cef_urlrequest_create:	https://spclient.wg.spotify.com/connect-state/v1/devices/79c0c40873f82eea794b84dd07b2b1279811e98b
[+] cef_urlrequest_create:	https://spclient.wg.spotify.com/connect-state/v1/devices/79c0c40873f82eea794b84dd07b2b1279811e98b

**Comment by abba23** [comment]
That's not it. The relevant line should be prefixed with `[-]`, because we're looking for something that's being blocked. The `gabo-receiver-service` line just indicates an unrelated analytics request.

**Comment by jackthiago** [comment]
yes but it doesn't appear any other lines when i try to click on a joe rogan episode

**Comment by abba23** [comment]
Does it still not work? Have you checked if you can play it without the adblocker? If there's nothing else in the logs, then I don't see how this could be caused by the adblocker.
