### ISSUE TITLE
it doesn't block ads or am I doing something wrong?

### ISSUE THREAD

**Issue by ArnoldasMk** [abba23/spotify-adblock-linux#97]
Hello, I installed spotify.deb and then I installed spotify-adblock-linux, but it doesn't block any ads....? Anyone can help me solve this problem? Thanks.

**Comment by abba23** [comment]
I'd need more info to be able to help you. How did you install Spotify? What was the terminal output when you went through the adblocker build/install steps and when running Spotify with it?

Your problem could be related to #95, which should be fixed now, so maybe just building and installing the adblocker again will make it work.

**Comment by Greatest125** [comment]
When you open Spotify, do you open it with 'LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify' in terminal?

**Comment by ArnoldasMk** [comment]
Sorry for late reply, I fixed it installing spotify.deb from spotify website. Thanks.
