### ISSUE TITLE
Won't open Spotify Facebook login ....

### ISSUE THREAD

**Issue by parataxia** [abba23/spotify-adblock-linux#98]
![image](https://user-images.githubusercontent.com/28812145/106558862-59ab2000-64d9-11eb-9fed-1ac40009368c.png)

Any ideas on updating Spotify for the latest repo to work with this project? It doesn't seem to work with latest Spotify either when I manually install it via snap and use the `.so` file with it. I am using latest Manjaro and repo from Github.

It seems to use different hooks at the entry level (I can't recall the wrapper function but no longer called `cef_urlrequest_create()` )

Thank you.

*EDIT* small log w/ details:
`dlsym (cef_urlrequest_create): /var/lib/snapd/snap/bin/spotify-adblock.so: undefined symbol: cef_urlrequest_create
2021/02/01 22:24:18.060723 system_key.go:147: cannot determine seccomp compiler version in generateSystemKey: invalid format of version-info: "dlsym (cef_urlrequest_create): /var/lib/snapd/snap/bin/spotify-adblock.so: undefined symbol: cef_urlrequest_create\nee847f803a5d5c519200f123fd5cb55357020f12 2.5.1 80ce90419d281437e5b8b03baec604016043649f7c00b7a578f5fc8afef1d29c bpf-actlog" `

**Comment by abba23** [comment]
The adblocker doesn't work with the snap Spotify package (as noted in the readme). If you didn't already, please try installing Spotify using the instructions at the bottom of [this page](https://www.spotify.com/us/download/linux).

**Comment by parataxia** [comment]
> The adblocker doesn't work with the snap Spotify package (as noted in the readme). If you didn't already, please try installing Spotify using the instructions at the bottom of [this page](https://www.spotify.com/us/download/linux).

Unfortunately I don't have apt with Manjaro (Arch Linux basically) but I am trying to set up a container with Debian so I can perhaps copy the latest binary to my local machine. What I noticed is the fact 1) Arch Linux no longer has a valid credential with Spotify and Facebook logins - although the regular logins probably wor. 2) You have to perhaps update the Spotify package with latest binary... but of course Spotify ceased their official repository updates.
Will update with further details later.

**Comment by abba23** [comment]
I don't really understand how your problems are supposed to be related to the adblocker.

Anyway, I'm not sure if it works on Manjaro, but I use the Spotify AUR package on Arch Linux, which just extracts and installs the files from the Debian package and should get you the latest version. This project can also be found in the AUR by the way (`spotify-adblock-git`).

**Comment by parataxia** [comment]
> I don't really understand how your problems are supposed to be related to the adblocker.
> 
> Anyway, I'm not sure if it works on Manjaro, but I use the Spotify AUR package on Arch Linux, which just extracts and installs the files from the Debian package and should get you the latest version. This project can also be found in the AUR by the way (`spotify-adblock-git`).

I think it comes up with 4 or so different build options of Spotify w/ `spotify-adblock-git`, all of them do *not* work with Facebook logins when I initially launch it after installation... it opens the browser but will not continue, alas, above image proves it. Although you probably use default login credentials instead? I think Spotify is jig-sawing the entire issue with Facebook token-IDs to make sure you cannot login using Facebook problems.

**Comment by abba23** [comment]
I just tested the Facebook login without adblocker and got the same error message as in your screenshot. I'll close this issue then, because it seems to be a general problem with Spotify that is unrelated to this adblocker.

**Comment by parataxia** [comment]
For future reference, if you make another account with strictly e-mail instead of Facebook, it is possible to transfer data from one account to another one using: https://github.com/Freebios/transfer-spotify-account

_CLOSED_
